import json
import os

with open('sketch-colured.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Update Cell 18 (Inference block)
cell_18_source = [
    'import torch\n',
    'from PIL import Image as PILImage\n',
    'import torchvision.transforms as transforms\n',
    'import torchvision.utils as vutils\n',
    'from ipywidgets import FileUpload\n',
    'from IPython.display import display, Image\n',
    'import io\n',
    'import os\n',
    '\n',
    'DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
    '\n',
    'gen = Generator(in_channels=3).to(DEVICE)\n',
    '\n',
    '# Try to find the weights in multiple possible locations (Working dir or Input dir)\n',
    '# PREVIOUS_VERSION_DIR, CHECKPOINT_GEN and FINAL_MODEL are defined in Cell 1\n',
    'PREVIOUS_GEN = os.path.join(PREVIOUS_VERSION_DIR, "gen.pth.tar")\n',
    '\n',
    'found = False\n',
    'if os.path.exists(FINAL_MODEL):\n',
    '    print(f"Loading Final Generator Model from {FINAL_MODEL}...")\n',
    '    gen.load_state_dict(torch.load(FINAL_MODEL, map_location=DEVICE))\n',
    '    found = True\n',
    'elif os.path.exists(CHECKPOINT_GEN):\n',
    '    print(f"Loading latest Checkpoint from {CHECKPOINT_GEN}...")\n',
    '    checkpoint = torch.load(CHECKPOINT_GEN, map_location=DEVICE)\n',
    '    gen.load_state_dict(checkpoint["state_dict"])\n',
    '    found = True\n',
    'elif os.path.exists(PREVIOUS_GEN):\n',
    '    print(f"Loading weights from Kaggle Input: {PREVIOUS_GEN}...\")\n',
    '    checkpoint = torch.load(PREVIOUS_GEN, map_location=DEVICE)\n',
    '    if \"state_dict\" in checkpoint:\n',
    '        gen.load_state_dict(checkpoint[\"state_dict\"])\n',
    '    else:\n',
    '        gen.load_state_dict(checkpoint)\n',
    '    found = True\n',
    '\n',
    'if not found:\n',
    '    print(\"[WARNING] No trained weights found! Check if you added the input dataset or if training has started.\")\n',
    '    print(f\"Searched in:\\n1. {FINAL_MODEL}\\n2. {CHECKPOINT_GEN}\\n3. {PREVIOUS_GEN}\")\n',
    '\n',
    '# gen.eval()  # Kept commented to ensure Dropout variance\n',
    '\n',
    'transform = transforms.Compose([\n',
    '    transforms.Resize(256),\n',
    '    transforms.CenterCrop(256),\n',
    '    transforms.ToTensor(),\n',
    '    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))\n',
    '])\n',
    '\n',
    'upload = FileUpload(accept=\"image/*\", multiple=False)\n',
    'display(upload)\n',
    '\n',
    'def colorize_image(upload):\n',
    '    if not upload.value:\n',
    '        return\n',
    '\n',
    '    # Handle different ipywidgets versions cleanly\n',
    '    try:\n',
    '        content = upload.value[0][\"content\"] if isinstance(upload.value, tuple) else list(upload.value.values())[0][\"content\"]\n',
    '    except Exception:\n',
    '        content = upload.value\n',
    '\n',
    '    img = PILImage.open(io.BytesIO(content)).convert(\"RGB\")\n',
    '\n',
    '    input_tensor = transform(img).unsqueeze(0).to(DEVICE)\n',
    '\n',
    '    with torch.no_grad():\n',
    '        output = gen(input_tensor)\n',
    '\n',
    '    vutils.save_image(output, \"generated_color.png\", normalize=True)\n',
    '\n',
    '    display(Image(\"generated_color.png\"))\n',
    '\n',
    '    print(\"Colored image saved to generated_color.png\")\n',
    '\n',
    'upload.observe(lambda change: colorize_image(upload), names=\"value\")\n'
]

nb['cells'][18]['source'] = cell_18_source

with open('sketch-colured.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
